create extension if not exists vector;

-- Create a table to store the embeddings
--
-- Notes: timezone must match those set in _config.yml in your Jekyll website.
create table page_embeddings (
  id bigint generated by default as identity primary key,
  uid varchar(255) not null unique,
  most_recent_edit timestamp with time zone default timezone('Europe/Rome'::text, now()) not null,
  content text,
  embedding vector(1536),
  metadata jsonb,
  created_at timestamp with time zone default timezone('Europe/Rome'::text, now())
);

-- Create a similarity search index
create index page_embeddings_embedding_idx
on page_embeddings
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- create a Postgres function to safely execute the similarity search
create or replace function cosine_similarity(query text)
returns table (
  title text,
  uid varchar(255),
  most_recent_edit timestamp with time zone,
  url text,
  date text,
  similarity numeric
)
language plpgsql
security definer
as $$
begin
  return query execute query;
end;
$$;
